sudo: required

services:
  - docker

language: python
python:
  - "3.8-dev"

script:
  - pip install PyGithub requests
    if: tag IS present
  - python build.py
    if: tag IS present
  - docker run --rm -it mrsipan/python:${TRAVIS_BRANCH} python3 -c "import ssl, ctypes, uuid, sqlite3"
    if: tag IS present
