sudo: required

services:
  - docker

language: python
python:
  - "3.8-dev"

script:
  - pip install PyGithub requests
  - python build.py
  - docker run --rm --it mrsipan/python:3.8.0 python3 -c "import ssl, ctypes, uuid, sqlite3"
